runtime: python39
entrypoint: gunicorn -b :$PORT main:app

# Auto scaling
instance_class: F1
automatic_scaling:
  max_instances: 10
  min_instances: 0
  # max_idle_instances:
  # min_idle_instances:
  target_cpu_utilization: 0.75
  target_throughput_utilization: 0.75
  max_concurrent_requests: 50
  # max_pending_latency:
  # min_pending_latency:

# Basic scaling
# instance_class: B1
# basic_scaling:
#   max_instances: 5
#   idle_timeout: 5m

# Manual scaling
# instance_class: B1
# manual_scaling:
#   instances: 5

# Default service name
service: default

handlers:
# Redirect all http requests to https
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
